### ISSUE TITLE
Project lacking explicit licensing

### ISSUE THREAD

**Issue by Bujiraso** [antirez/redis-io#102]
Hi there!

I notice when I reached this GitHub page that there's no explicit LICENSE or COPYING file in the root of the project. Also, on the README, there is no explicit licensing information.

I managed to find a few places where redis was listed as "open source" ([here](http://redis.io/topics/twitter-clone)), and on [this](http://redis.io/topics/license) page it says that everything Redis is governed under three clause BSD -- which is great! But in this repo all I could spot regarding that was buried at the bottom of [this](https://github.com/antirez/redis-io/blob/master/views/documentation.md) file.

Not too big a deal, but just a thought that could shave a few minutes of searching for others like myself who were looking to use the site or its code samples in their projects.

Thanks!

**Comment by djanowski** [comment]
There is a COPYING file. Thanks.

**Comment by Bujiraso** [comment]
Hi there,

Could you point out this file?

I don't see one in the repository at all.
``` 
$ find redis-io/ -name *COPYING*
$ git grep COPYING
$
```

Is it not on the master branch? Perhaps a commit with the COPYING file didn't get pushed.

Thanks!
