### ISSUE TITLE
typo in the srandmember command page

### ISSUE THREAD

**Issue by zhkzyth** [antirez/redis-io#103]
hi,i just read the command `srandmember`, and find typo in the [srandmember](http://redis.io/commands/srandmember) command page.The word `bucked` should be `bucket`, which occurs in the sentence `Once a non empty bucket is found, since we use chaining in our hash table implementation, the number of elements inside the bucked is checked and a random element is selected.`

**Comment by itamarhaber** [comment]
Hi @zhkzyth - to correct such typos just make a pull request with the correction at https://github.com/antirez/redis-doc/blob/master/commands/srandmember.md and the maintainers will merge it. Thanks.
