### ISSUE TITLE
Encoding::CompatibilityError at /commands/DUMP

### ISSUE THREAD

**Issue by filimonov** [antirez/redis-io#106]
[https://redis.io/commands/DUMP](https://redis.io/commands/DUMP)

Encoding::CompatibilityError at /commands/DUMP
incompatible character encodings: ASCII-8BIT and UTF-8

Ruby 	/srv/redis-io/.gs/gems/haml-3.1.4/lib/haml/buffer.rb: in push_text, line 118
Web 	GET 127.0.0.1/commands/DUM

**Comment by djanowski** [comment]
Fixed, thank you.
