### ISSUE TITLE
redis.io certificate expiration

### ISSUE THREAD

**Issue by mikizuv** [antirez/redis-io#117]
redis.io site certificate about to expire:
https://www.sslshopper.com/ssl-checker.html#hostname=redis.io

**Comment by antirez** [comment]
@djanowski please could you give me hints about how to proceed? Thanks!

**Comment by antirez** [comment]
Thanks, fixed.

**Comment by reallyimeric** [comment]
expired again... @antirez

**Comment by djanowski** [comment]
The cron job doesn't seem to be reloading Nginx as we want... Fixed, thank
you.
