### ISSUE TITLE
Keep the commands bar when viewing a command

### ISSUE THREAD

**Issue by Sembiance** [antirez/redis-io#12]
So when you are on the commands page: http://redis.io/commands

You have a nice helpful bar at the top listing each category of commands: All Keys Strings Hashes etc.

As soon as you select an individual command though this bar goes away.

It would be really nice if this command category bar remained when looking at specific individual commands.

**Comment by djanowski** [comment]
It's a lot of real estate, especially on mobile. Thank you for your suggestion.
