### ISSUE TITLE
SSL Cert Expired

### ISSUE THREAD

**Issue by tystr** [antirez/redis-io#127]
Looks like the SSL cert for redis.io is expired

**Comment by oldmud0** [comment]
Yep, it expired just a few hours ago. That's a funny coincidence.

**Comment by djanowski** [comment]
Shit. For some reason Nginx is not reloading after Certbot renews the certificate. Thank you.

**Comment by akiraho** [comment]
this happens again; cert expired:)

**Comment by djanowski** [comment]
Done!
