### ISSUE TITLE
Feature request - nav improvment

### ISSUE THREAD

**Issue by chrislovecnm** [antirez/redis-io#14]
Hi ... just a thought

When I am on http://redis.io/commands/sadd or other command pages can we have the menu that is on http://redis.io/commands

 All Keys Strings Hashes Lists Sets Sorted Sets Pub/Sub Transactions Scripting Connection Server

It would be awesome for nav :)

Is this the code?

 %nav
    %a(href="#") All

    - Reference::GROUPS.each do |name, description|
      %a(href="##{name}")= description

Thanks

Chris

**Comment by djanowski** [comment]
Fixed by now.
