### ISSUE TITLE
Typo in GEORADIUS docs

### ISSUE THREAD

**Issue by doublesharp** [antirez/redis-io#141]
The [GEORADIUS](https://redis.io/commands/georadius) documentation has a typo:

> The common use case for this command is to retrieve geospatial items near a specified point **and no far** than a given amount of meters (or other units). 

Should be:

>The common use case for this command is to retrieve geospatial items near a specified point **not farther** than a given amount of meters (or other units). 

I wasn't able to find this content to update and submit a pull request :(

**Comment by itamarhaber** [comment]
You can submit the PR at https://github.com/antirez/redis-doc for commands/georadius.md

**Comment by doublesharp** [comment]
@itamarhaber Thanks, done!

**Comment by itamarhaber** [comment]
@doublesharp great, please also close this issue in that case :)
