### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by daguej** [antirez/redis-io#146]
The redis.io cert is expired [again](https://github.com/antirez/redis-io/issues?q=is%3Aissue+certificate).

Let's Encrypt has many options for automatically updating the cert; consider setting one up.

**Comment by djanowski** [comment]
Fixed. The certificate is actually renewing correctly, the problem is that
Nginx doesn't restart.

**Comment by daguej** [comment]
Ah, that's a pain.  Certbot?
