### ISSUE TITLE
The SYNC command documentation is empty

### ISSUE THREAD

**Issue by hashhar** [antirez/redis-io#149]
Please see https://redis.io/commands/sync.

It returns no data.

<img width="1440" alt="screen shot 2018-07-27 at 12 54 03 am" src="https://user-images.githubusercontent.com/10473142/43283828-99947acc-9137-11e8-94ee-5c1a1686fc9d.png">

**Comment by itamarhaber** [comment]
Hello @hashhar 

Yes, this a known issue waiting for a resolution via PR https://github.com/antirez/redis-doc/pull/940
