### ISSUE TITLE
Let's Encrypt Certificate is expired (October 16 2018)

### ISSUE THREAD

**Issue by jeremyjung** [antirez/redis-io#158]
The nginx issue described in #146 has still not been resolved so the cert expires every two months.

**Comment by hydrapolic** [comment]
Seems unfortunate that it happens the day when v5.0 should be released: https://www.ssllabs.com/ssltest/analyze.html?d=redis.io&latest

**Comment by hydrapolic** [comment]
It's fixed now

**Comment by jeremyjung** [comment]
Cool
