### ISSUE TITLE
Redis.io Expired SSL Certificate

### ISSUE THREAD

**Issue by joeneldeasis** [antirez/redis-io#175]
To whom it may concern, please renew the SSL Certificate of redis.io cause it is already expired right now. Thanks

![image](https://user-images.githubusercontent.com/7831102/56107951-a677dc80-5f7b-11e9-9f8f-d79f674decc7.png)

**Comment by ziggythehamster** [comment]
And again today (ACME must not be configured correctly):

![image](https://user-images.githubusercontent.com/66674/66692281-cc8fe800-ec51-11e9-8363-bc17c37b6a20.png)

**Comment by joeneldeasis** [comment]
Closing this now, it's been 6 months ago and already fixed. Thanks
