### ISSUE TITLE
Certificate for redis.io expired

### ISSUE THREAD

**Issue by wooque** [antirez/redis-io#200]

**Comment by itamarhaber** [comment]
Thanks for reporting this @wooque - this should be resolved soon™

**Comment by OrangeDog** [comment]
Having happened three years in a row, perhaps you should add some monitoring / automation.

**Comment by itamarhaber** [comment]
Thanks for making the suggestion @OrangeDog - that's definitely something to consider.

**Comment by itamarhaber** [comment]
@wooque please verify that the issue has been resolved.

**Comment by wooque** [comment]
@itamarhaber yeah, it resolved
