### ISSUE TITLE
Add a cache manifest

### ISSUE THREAD

**Issue by kevincox** [antirez/redis-io#25]
It would be nice to have a cache manifest for redis.io.  This way the docs could be viewed offline.  I know the docs can be downloaded manually but it would be convenient to just type redis.io in your browser.

This also has the advantage of speeding up page loads and reducing server load.

I'm not sure exactly what should be downloaded on visit but I think it should be at least the command reference and possibly cache articles when visited.

**Comment by djanowski** [comment]
I'll take a patch :)
