### ISSUE TITLE
redis.io/topics/config out of date

### ISSUE THREAD

**Issue by kelunik** [antirez/redis-io#54]
> ### [Changing Redis configuration while the server is running](http://redis.io/topics/config)

> Note that modifying the configuration on the fly has no effects on the redis.conf file so at the next restart of Redis the old configuration will be used instead.

> Make sure to also modify the redis.conf file accordingly to the configuration you set using CONFIG SET. There are plans to provide a CONFIG REWRITE command that will be able to run the redis.conf file rewriting the configuration accordingly to the current server configuration, without modifying the comments and the structure of the current file.

This section is out of date, `CONFIG REWRITE` has been introduced in version 2.8.

**Comment by djanowski** [comment]
Can you provide a patch?

**Comment by antirez** [comment]
Thanks, fixing this myself, just a minute.

**Comment by antirez** [comment]
Fixed in 01300a2 (redis-doc repo). Thanks.
