### ISSUE TITLE
Related Comments aren't all clickable

### ISSUE THREAD

**Issue by dkullmann** [antirez/redis-io#62]
While at http://redis.io/commands/sadd I am able to click some of the related commands, but not all. In the image below you can see "SDIFF" is clickable, but "SDIFFSTORE" is not.

![image](https://cloud.githubusercontent.com/assets/422899/6219431/3fcdcf12-b5f7-11e4-8d20-6ed854a6a736.png)

**Comment by dkullmann** [comment]
It appears this is affecting links which are covered by the content on the left, in the page I linked this includes `#return-value`, `#history`, `#examples`:

![image](https://cloud.githubusercontent.com/assets/422899/6219517/99715236-b5f8-11e4-907b-fc2a6bf685f6.png)

**Comment by dkullmann** [comment]
Looks like this was due to `position: relative` being set on the `h2` tags, which meant they appeared "on top" of the `aside` links which don't have a position attribute or z-index set. The `position: relative` is needed for the anchor links (the asterisks) on the h2's so removing it would mean thinking of another implementation for the anchor tags.

Another option would be to add `position: relative` to the `aside` and increase it's z-index so it's above the `h2`s. I'm sorry I can' test and submit a PR as I don't have everything setup locally.

**Comment by mattsta** [comment]
Yeah, same as https://github.com/antirez/redis-io/pull/61 and https://github.com/antirez/redis-io/commit/e7d70b184e5eee6de049fa7f0ee031516197b823#commitcomment-9743357

**Comment by dkullmann** [comment]
thanks @mattsta !

**Comment by mattsta** [comment]
Oh, don't thank me.  I broke it, but I don't have access to fix it.  :)

**Comment by kristinpeterson** [comment]
@dkullmann - I had been working on a fix for this locally and came to the same conclusion.  (see: #63)
