### ISSUE TITLE
Some of Redis' longer commands are cropped in the side article

### ISSUE THREAD

**Issue by itamarhaber** [antirez/redis-io#65]
I feel like a :toilet: because I'm opening an issue without suggesting a fix:

![capture](https://cloud.githubusercontent.com/assets/6059516/6657847/745e8842-cb60-11e4-9bff-cf6dc9bbc1ff.PNG)

**Comment by djanowski** [comment]
This is fixed in master now.

**Comment by itamarhaber** [comment]
:beer:
