### ISSUE TITLE
Autolinking can be too zealous

### ISSUE THREAD

**Issue by itamarhaber** [antirez/redis-io#72]
In some cases autolinking can behave too fanatically. For example, eval.md discusses the `KEYS` array and autolink links it to the command.

@badboy had suggested prefixing with a `!` hence https://github.com/antirez/redis-doc/pull/562 which currently fails.

**Comment by badboy** [comment]
Test only failed because we still didn't fix the spelling-checks.

**Comment by djanowski** [comment]
I think this is working as expected.
