### ISSUE TITLE
error style 

### ISSUE THREAD

**Issue by jacket-code** [antirez/redis-io#73]
when i run this server, and start up, then i get the fallowing error, how to solve it ? thank you

Sass::SyntaxError: Illegal nesting: Nothing may be nested beneath mixin directives.
    views/styles.sass:62
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:811:in `parse_mixin_include'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:640:in`parse_directive'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:551:in `parse_line'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:456:in`build_tree'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:475:in `block in append_children'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:474:in`each'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:474:in `append_children'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:330:in`_to_tree'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:300:in `_render'
    /usr/local/rvm/gems/ruby-2.1.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:247:in`render'
    /usr/local/rvm/gems/ruby-2.1.2/gems/tilt-1.4.1/lib/tilt/css.rb:24:in `evaluate'
    /usr/local/rvm/gems/ruby-2.1.2/gems/tilt-1.4.1/lib/tilt/template.rb:103:in`render'
    /usr/local/rvm/gems/ruby-2.1.2/gems/cuba-2.2.1/lib/cuba.rb:115:in `render'
    /home/winkt/code/redisProject/redis-io-master/app.rb:108:in`render'
    /home/winkt/code/redisProject/redis-io-master/app.rb:253:in `block (2 levels) in <top (required)>'
    /usr/local/rvm/gems/ruby-2.1.2/gems/cuba-2.2.1/lib/cuba.rb:158:in`block in on'

**Comment by djanowski** [comment]
Did you try installing the gems listed in `.gems`?

You can try this:

    $ gem install $(sed -e 's/ -v /:/' .gems)

**Comment by jacket-code** [comment]
I do what you want me to do, but still the same error, 
>gem install $(sed -e 's/ -v /:/' .gems)
error is : 
Sass::SyntaxError: Illegal nesting: Nothing may be nested beneath mixin directives.
	views/styles.sass:62
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:811:in `parse_mixin_include'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:640:in `parse_directive'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:551:in `parse_line'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:456:in `build_tree'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:475:in `block in append_children'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:474:in `each'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:474:in `append_children'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:330:in `_to_tree'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:300:in `_render'
	/usr/local/rvm/gems/ruby-2.2.2/gems/haml-3.1.4/vendor/sass/lib/sass/engine.rb:247:in `render'

**Comment by itamarhaber** [comment]
Getting the same behavior - Ubuntu 14.04

Using rvm and did `apt-get install libxslt-dev libxml2-dev` to get nokogiri:1.5.2 to install.

**Comment by itamarhaber** [comment]
@djanowski any ideas?

**Comment by badboy** [comment]
So because of the unusual setup `redis-io` uses it's sadly not a "just works" way of getting started.

You need:

* Ruby 1.9.3 (use rvm or rbenv or a vm to install it globally) [the used nokogiri version doesn't work with anything newer, a newer nokogiri might work, I didn't test it though)
* The exact versions of gems listed in [`.gems`](https://github.com/antirez/redis-io/blob/master/.gems)
* Make sure no other versions of the gems are listed.

Sadly we're relying on Ruby's default `require` behaviour, which loads whatever matching gem it finds first and if you got several versoins of `tilt` installed, this bites you.

**Comment by badboy** [comment]
Oh, and make sure you have only a sass version < 3.3.0, otherwise it breaks with the above error

**Comment by itamarhaber** [comment]
> make sure you have only a sass version < 3.3.0

That did the trick (or rather `gem uninstall --version 3.4.20`) :beers:
