### ISSUE TITLE
Redis 3.0 for Windows?

### ISSUE THREAD

**Issue by birarich** [antirez/redis-io#80]
When we will get stable Redis 3.0 for Windows OS?

**Comment by enricogior** [comment]
@birarich 
this is not the repository to ask for Redis on Windows, you can find the latest news on Redis on Windows 3.0 scrolling down this issue https://github.com/MSOpenTech/redis/issues/231 
Or simply check the Redis on Windows release page: https://github.com/MSOpenTech/redis/releases
Thank you.
