### ISSUE TITLE
extra margin on Developer Day callout

### ISSUE THREAD

**Issue by stockholmux** [antirez/redis-io#81]
At desktop resolutions, there is a weird margin on the callout about Redis Developer Day. 
<img width="235" alt="screen shot 2015-10-04 at 10 26 59 am" src="https://cloud.githubusercontent.com/assets/1152927/10268309/7ec8dffa-6a82-11e5-9194-ed7c93a5c9e1.png">

I'm not able to build the entire site, but I think the problem lies in the style for `aside` in `topics.sass`. It seems like this style should only apply to `aside` elements in `site-content`. I'm guessing that changing the selector on line 73 from `aside` to `.site-content aside` will resolve the problem.

**Comment by djanowski** [comment]
Thanks anyway.
