### ISSUE TITLE
Keyspace Notifications SET documentation mildly confusing

### ISSUE THREAD

**Issue by trasa** [antirez/redis-io#83]
On URL http://redis.io/topics/notifications

Under "Configuration" we see the list of notify-keyspace-events values, such as "s" for "Set Commands" and so on.

Further down it says "SET and all its variants [...] generate _set_ events." But of course to see these events happen you need to have "$" String commands enabled, and not "s" Set commands. The confusion comes from using SET as a verb in this case, vs. set as a noun previously. Once you see it, it's obvious.

**Comment by djanowski** [comment]
We'll take a patch! Thank you.
