### ISSUE TITLE
Redis requires Password suddenly.

### ISSUE THREAD

**Issue by hochmann** [antirez/redis-io#86]
Redis Version = 2.8.17

Redis was already more than 3 months in use, and installed via chef cookbook (default chef supermarket cookbook).

since last week i started to get the following error on all my environments: 
Uncaught exception 'Redis​Exception' with message 'Failed to AUTH connection' in /​var/​www/​shared/​t​3​sources/​typo​3_​src-​6.​2.​15/​typo​3/​sysext/​core/​Classes/​Cache/​Backend/​Redis​Backend.​php:​152

The Problem was reappearing after few hours all over again.

My Redis Configuration file has no requirepass:

```
################################## SECURITY ###################################

# Require clients to issue AUTH <PASSWORD> before processing any other
# commands.  This might be useful in environments in which you do not trust
# others with access to the host running redis-server.
#
# This should stay commented out for backward compatibility and because most
# people do not need auth (e.g. they run their own servers).
#
# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
#
# requirepass foobared
```

What should i do? ​

**Comment by djanowski** [comment]
See https://gist.github.com/antirez/12d60c950fbfd8c8837e
