### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by wjdavis5** [antirez/redis-io#94]
Ubuntu 16.04 - fresh install, only ssh and build-essentials (with tcl obviously) running in virtual box with 768 MB RAM and 1 Core.

 [err]: With min-slaves-to-write: master not writable with lagged slave in te                                                                                                       sts/integration/replication-4.tcl

!!! WARNING The following tests failed:

*** [err]: With min-slaves-to-write: master not writable with lagged slave in te                                                                                                       sts/integration/replication-4.tcl
Expected 'NOREPLICAS*' to equal or match 'OK'
Cleanup: may take some time... OK
Makefile:215: recipe for target 'test' failed
make[1]: *** [test] Error 1
make[1]: Leaving directory '/home/synovia/redis-3.2.0/src'
Makefile:6: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by arman-p** [comment]
I have this problem too. fresh installation of 16.04..

**Comment by georgeha** [comment]
Try to install and run make test again.

Worked for me!
